### ISSUE TITLE
Example code not correct

### ISSUE THREAD

**Issue by schneems** [reddavis/Campfire-Bot#1]
Took me a little while to find this, but 

```
msg("Im very well thank-you")
```

should be:

```
bot.msg("Im very well thank-you")
```

otherwise the self keyword is set to a tinder instance instead of a campfire instance

**Comment by schneems** [comment]
thanks for writing this up btw

**Comment by reddavis** [comment]
Thanks and no problem 

http://github.com/reddavis/Campfire-Bot/commit/c06127efdf715e200648d16748b685a02d012a63
